image: isi22/my-maven-chrome-image3:latest

stages:
  - setup
  - test
  - report

setup:
  stage: setup
  tags:
    - my-docker-runner
  script:
    - mvn clean compile

test:
  stage: test
  tags:
    - my-docker-runner
  script:
    - mvn test -Dbrowser=firefox
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

report:
  stage: report
  tags:
    - my-docker-runner
  script:
    - echo "Generating report..."
